# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/configuration/app.html

# The name of this app. Must be unique within a project.
applications:
  drupal:
    type: 'composable:25.05'
    stack:
      - php@8.3:
          extensions:
            - opcache
            - redis
            - sodium
            - apcu
            - blackfire
            - imagick
      - gnupg
      - patch
      - duplicity
      - python3
      - upsun
      - python3Packages.numpy
      - python3Packages.boto3
      - php83Extensions.mbstring
      - php83Extensions.iconv
      - php83Extensions.redis
      - php83Extensions.opcache
      - php83Extensions.sodium
      - php83Extensions.apcu
      - php83Extensions.blackfire
      - php83Extensions.imagick
    variables:
      env:
        # Skip automatic config import
        SKIP_CONFIG_IMPORT: 1
        ENABLE_SSL: 1
        # Set caching to Redis by default. Can be changed to 'ArrayCache' in dev/staging.
        CIVICRM_CACHING_TYPE: 'Redis'

        CIVICRM_CRED_KEYS: ''
        CIVICRM_SIGN_KEYS: ''
        CIVICRM_SITE_KEY: ''
        # Upsun project ID. Needed to identify the project in automated tasks.
        PROJECT_ID: ''
        # Authentication token for git repositories
        COMPOSER_AUTH: ''

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
    relationships:
        database: 'db:mysql'
        civicrm: 'db:civicrm'
        redis: 'cache:redis'

# The size of the persistent disk of the application (in MB).

# The 'mounts' describe writable, persistent filesystem mounts in the application.
    mounts:
        # The default Drupal files directory.
        '/web/sites/default/files':
            source: instance
            source_path: 'files'
        # Drupal gets its own dedicated tmp directory. The settings.platformsh.php
        # file will automatically configure Drupal to use this directory.
        '/tmp':
            source: instance
            source_path: 'tmp'
        # Private file uploads are stored outside the web root. The settings.platformsh.php
        # file will automatically configure Drupal to use this directory.
        '/private':
            source: instance
            source_path: 'private'
        # CiviCRM templates_c
        '/web/sites/default/civicrm/templates_c':
            source: instance
            source_path: 'templates_c'
        # Drupal php cache
        '/web/sites/default/php':
            source: instance
            source_path: 'php'
        # Drush needs a scratch space for its own caches.
        '/.drush':
            source: instance
            source_path: 'drush'
        # Drush will try to save backups to this directory, so it must be
        # writeable even though you will almost never need to use it.
        '/drush-backups':
            source: instance
            source_path: 'drush-backups'
        # Drupal Console will try to save backups to this directory, so it must be
        # writeable even though you will almost never need to use it.
        '/.console':
            source: instance
            source_path: 'console'

# Configuration of the build of this application.
    build: {}
    # The hooks executed at various points in the lifecycle of the application.
    hooks:
        # The build hook runs after Composer to finish preparing up your code.
        # No services are available but the disk is writeable.
        build: |
            set -e
            #Run Composer install
            composer install --no-dev --prefer-dist --no-progress --no-interaction

        # The deploy hook runs after your application has been deployed and started.
        # Code cannot be modified at this point but the database is available.
        # The site is not accepting requests while this script runs so keep it
        # fast.

        #Move s3Backup to a script
        deploy: |
            set -e
            php ./drush/platformsh_generate_drush_yml.php
            # if drupal is installed, will call the following drush commands:
            #   - `cache-rebuild`
            #   - `updatedb`
            #   - and if config files are present, `config-import`
            cd web
            bash $PLATFORM_APP_DIR/drush/platformsh_deploy_drupal.sh

# The configuration of app when it is exposed to the web.
    web:
        locations:
            # All requests not otherwise specified follow these rules.
            # Allow Mosaico HTML templates to be loaded.
            '/sites/default/civicrm/extensions':
                root: 'web/sites/default/civicrm/extensions'
                allow: true
                scripts: false
                expires: 15m
                passthru: false
            '/':
                # The folder from which to serve static assets, for this location.
                #
                # This is a filesystem path, relative to the application root.
                root: 'web'

                # How long to allow static assets from this location to be cached.
                #
                # Can be a time in seconds, or -1 for no caching. Times can be
                # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
                # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
                # 365 days).
                expires: 5m

                # Redirect any incoming request to Drupal's front controller.
                passthru: '/index.php'

                # Deny access to all static files, except those specifically allowed below.
                allow: false

                # Rules for specific URI patterns.
                rules:
                    # Allow access to common static files.
                    '\.(avif|webp|jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                        allow: true
                    '^/robots\.txt$':
                        allow: true
                    '^/sitemap\.xml$':
                        allow: true

                    # Deny direct access to configuration files.
                    '^/sites/sites\.php$':
                        scripts: false
                    '^/sites/[^/]+/settings.*?\.php$':
                        scripts: false
                    '^/update\.php$':
                        scripts: false
                    '^/cron\.php$':
                        scripts: false
                    '^/install\.php$':
                        scripts: false

            # The files directory has its own special configuration rules.
            '/sites/default/files':
                # Allow access to all files in the public files directory.
                allow: true
                expires: 5m
                passthru: '/index.php'
                root: 'web/sites/default/files'

                # Do not execute PHP scripts from the writeable mount.
                scripts: false

                rules:
                    # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                    '^/sites/default/files/(css|js)':
                        expires: 2w
                    '^/sites/default/files/civicrm/(ConfigAndLog|upload|templates_c|custom)':
                        allow: false


    crons:
      # Run Drupal's cron tasks.
      job_execute:
        spec: '*/30 * * * *'
        commands:
          start: |
                cd web
                drush --name='Cron User' civicrm:api job.execute auth=0 --yes
      job_process_mailing:
        spec: '*/5 * * * *'
        commands:
          start: |
                cd web
                drush --name='Cron User' civicrm:api job.process_mailing auth=0 --yes
      drupal_cron:
        spec: '0 */1 * * *'
        commands:
          start: |
                cd web
                drush cron --yes
    source:
      operations:
        auto-update:
          command: |
            curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
routes:
  "https://{default}/":
      type: upstream
      upstream: "drupal:http"
      cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

  "https://www.{default}/":
      type: redirect
      to: "https://{default}/"
services:
  db:
    type: mariadb:11.8
    configuration:
      properties:
        max_allowed_packet: 64
        max_heap_table_size: 32
        table_definition_cache: 2000
        table_open_cache: 2000
        default_charset: utf8mb4
        default_collation: utf8mb4_unicode_ci
        innodb_adaptive_hash_index: 0
        optimizer_use_condition_selectivity: 4
      schemas:
        - main
        - civicrm
      endpoints:
        mysql:
          default_schema: main
          privileges:
            main: admin
            civicrm: admin
        civicrm:
          default_schema: civicrm
          privileges:
            main: admin
            civicrm: admin

  cache:
      type: redis:7.2
